apiVersion: apps/v1
kind: Deployment
metadata:
  name: replay-hub-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: replay-hub-bot
  template:
    metadata:
      labels:
        app: replay-hub-bot
    spec:
      containers:
        - name: replay-hub-bot
          image: docker.io/keanuwatts/theclusterflux:replay-hub-bot
          env:
            - name: REPLAY_HUB_DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: replay-hub-discord-bot-token
                  key: DISCORD_BOT_TOKEN
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: replay-hub-bot
spec:
  selector:
    app: replay-hub-bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
